export const lightTheme = {
  body: "#FFF",
  text: "#363537",
  toggleBorder: "#FFF",
  background: "#363537",
  cardText: "#363537",
  navbarFooterBackground: "whitesmoke",
  footerLinkColor: "rgba(0, 0, 0, 0.3)",
  footerLinkColorHover: "rgba(0, 0, 0, 0.5)",
  navbarButtonBackground: "whitesmoke",
  navbarButtonBackgroundHover: "white",
  cardBtn: "whitesmoke",
  cardBtnHover: "white",
  paginationBackground: "whitesmoke",
  paginationBtnBorder: "whitesmoke",
  paginationBtnBackground: "whitesmoke",
  paginationBtnBackgroundHover: "rgba(0, 0, 0, 0.1)",
  themeTogglerBtn: "whitesmoke",
  themeTogglerBtnHover: "white",
};

export const darkTheme = {
  body: "#363537",
  text: "#FAFAFA",
  toggleBorder: "#6B8096",
  background: "#999",
  cardText: "#363537",
  navbarFooterBackground: "#242426",
  footerLinkColor: "#babebe",
  footerLinkColorHover: "#FFF",
  navbarButtonBackground: "#363537",
  navbarButtonBackgroundHover: "rgba(0, 0, 0, 0.5)",
  cardBtn: "#242426",
  cardBtnHover: "#34343a",
  paginationBackground: "#242426",
  paginationBtnBorder: "white",
  paginationBtnBackground: "#34343a",
  paginationBtnBackgroundHover: "rgba(0, 0, 0, 0.1)",
  themeTogglerBtn: "rgba(0, 0, 0, 0.5)",
  themeTogglerBtnHover: "#363537",
};
